export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLOSE_ALERT = "CLOSE_ALERT";
export const SEARCH_INPUT_VALUE_CHANGED = "SEARCH_INPUT_VALUE_CHANGED";
export const RECEIVED_USERS_RESULT = "RECEIVED_USERS_RESULT";
export const START_SEARCH_USERS_BY_NAME = "START_SEARCH_USERS_BY_NAME";
export const CLEAR_USERS_RESULT = "CLEAR_USERS_RESULT";
export const RECEIVED_ONE_USER_DETAILS = "RECEIVED_ONE_USER_DETAILS";